### PR TITLE
Higher-resolution icons

### PR DESCRIPTION
**Pull request by bwiernik**
Makes the icons tolerable on high-DPI screens. Would still be better to package the Add-in so that multiple icon sizes are available.

### CODE REVIEW

**Comment by bwiernik** [comment]
When approved, I can make parallel changes to Word for Mac and LibreOffice templates.

**Comment by dstillman** [comment]
Thanks for working on these, but let's hold off on this — it seems like other than the Z these are upscaled from the smaller graphics, which just makes them blurrier at all sizes, including on non-high-res displays.

We have a designer who can make new icons for the plugins across the board.

**Comment by bwiernik** [comment]
The changes here are basically to take 64px icons from the MSO image gallery and swap in the Z for the standard inset picture (so they are designed for high-res displays). I mostly made them for my personal use to make using the integration more pleasant for me.

If you have a designer create a set of new icons, it would be nice to have icons drawn for each of the major sizes (16px, 32px, 48px, 64px, 128px) so that they could be included eventually in a packaged Office Add-in that could then dynamically choose the correct size icon (rather than the status quo where only one size can be specified, leading to poor scaling on either high-res or standard displays or for large/small icons).
https://docs.microsoft.com/en-us/office/dev/add-ins/design/design-icons

**Comment by bwiernik** [comment]
(And to to be clear, the changes here are just to the ZoteroAddEditCitation0.png ZoteroAddEditBibliography.png icons. The "32" icons are the existing 32px icons in the add-ins.

**Comment by dstillman** [comment]
Right, the parts that you made (e.g., the Z) look fine, but I'm pretty sure the originals were upscaled (not by you) — they're much blurrier than they should be. That includes on low-res displays, where they're much blurrier than you might expect from the normal scaling effects of a shrunk-down high-res image. (In other words, if these were truly 64px icons, they would look worse at 32px on low-res displays than the original 32px ones, but not this much worse.)

I'll check with our designer to see how feasible this is.

**Comment by bwiernik** [comment]
I’m guessing the blurrieness you are seeing is because these icons have the fine lines from the 64px icons, which might be only 1px on smaller resolutions. The existing 32px icons I drew the lines double wide so that they could work reasonably well at both 32px and 16px (while not being the best for either).

**Comment by bwiernik** [comment]
Also, not being defensive or anything. Just trying to give you all the information I can to help your decision making.

**Comment by dstillman** [comment]
No, again, this isn't something you did. The original images just don't seem to have been natively drawn at 64px — they're pretty clearly anti-aliased at full size. (You can tell in particular from the curved white lines on the yellow book — nobody would draw that sort of anti-aliasing by hand.)

**Comment by adomasven** [comment]
https://docs.microsoft.com/en-us/office/dev/add-ins/design/design-icons this does not apply to us. I am not sure we can even use the JS based add-in API to integrate with Zotero, but even if we could, it would require us to rewrite major parts of the add-in. Last time I [checked](https://github.com/zotero/zotero-word-for-windows-integration/pull/28#issuecomment-288698341), I found out that the the current API we use is very limited in what can be done. I think we might be able to load different DPI icons if we have their absolute paths, but it's kinda complicated and not worth the effort.

Having said that, I suspect the majority of our userbase mirrors that of the general population, meaning that most people are on low resolution screens like 1366x768 which couldn't be hi-dpi, which suggests that we should be optimizing for low-dpi, 32px icons for now.

Actually, having written this, we could detect the screen DPI in Zotero and automatically install a template with appropriately sized icons, but that would mean duplicating the template files (a reasonable compromise in my opinion).

**Pull request closed without merging**
