### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by bwiernik**
Four changes:

1. Replaces icons with ones that resize (for user customization of
ribbon and Quick Access Toolbar) and invert colors (in Word 2016) more
aesthetically nicely. For remove field codes, I used a stock icon. For
Citation and Bibliography, I made icons that resemble the built-in Word
citation and bibliography buttons with Zotero branding.

2. Also includes secondary versions of the Citation, Bibliography, and
Doc Preferences macros with alternative sized icons (small or large).
These are useful for user customizations. It’s not possible to supply
both formats to the same ribbon button using Ribbon XML.

3. Add Zotero app icon to the Ribbon group to show during automatic
resizing or when the group is added to QAT.

4. Combine the two bibliography functions into a single Add/Edit
Bibliography button. This would seem to simplify the user experience a
lot ala the combined citation button. This will require adding the
corresponding command to integration.js in zotero/zotero. I’m not
familiar enough with the integration.js to make that addition. Is there
interest in moving in this direction?

(I added the Add/Edit Bibliography command to Zotero.dot, but I don’t
have access to Word 2003 to edit the toolbar.)

### CODE REVIEW

**Comment by bwiernik** [comment]
@adamosven Just wanted to be sure you saw this.

**Comment by adomasven** [comment]
I have (although you've misspelt my handle :) ). I intend to start working on windows word integration shortly, starting with this branch. Thanks for contributing!

The only comment I have now is that if you modify the template files for Word integration you should run `build/template/unpack_templates.sh` before committing (as noted in Readme.md). It's okay to force push onto this branch, if you want to do that.

**Comment by bwiernik** [comment]
Sorry about the misspelling :). I unpacked the templates.

**Comment by adomasven** [comment]
Ok, so some questions first:

> Also includes secondary versions of the Citation, Bibliography, and
Doc Preferences macros with alternative sized icons (small or large).
These are useful for user customizations. It’s not possible to supply
both formats to the same ribbon button using Ribbon XML.
1. Why would we want to supply both formats to the ribbon buttons (if at all)?
1. What is the advantage of having multiple sizes of icons? The larger icons look better for me in QAT and it makes the Ribbon customization preferences confusing. 
image
1. This is addressing #16 , right? Most of these icons look good on the dark theme, except for the preferences ones. And Word seems to invert colours for the Unlink icon. Could we get the gear to invert too somehow?
image


> Combine the two bibliography functions into a single Add/Edit
Bibliography button. This would seem to simplify the user experience a
lot ala the combined citation button.

I like the idea of this. Will look into integrating.

> (I added the Add/Edit Bibliography command to Zotero.dot, but I don’t
have access to Word 2003 to edit the toolbar.)

I'll look into it and we can update the interface. Word 2003 is probably not used too much by this point (although still installs and runs well on Windows 10!), but porting these and improving the UI for LibreOffice would be nice. 

-----

CC @dstillman @stakats @fcheslack @johanneskrtek
Any opinions on the new look?
image
Compared to the old one:
image

New look inspired by Word 2016 icons:
image

**Comment by bwiernik** [comment]
> 1. Why would we want to supply both formats to the ribbon buttons (if at all)?
>2. The larger icons look better for me in QAT and it makes the Ribbon customization preferences confusing.

Sorry, I wasn't clear in my explanation. What I meant was that it was not possible to supply both a large and small format image to the same button using Office's RibbonXML syntax. So, you can't give the button both sizes and have it choose the appropriate one based where the icon is being shown. Instead, when you supply a large (32x32) icon and place the button in a small slot (e.g., on the QAT), Word automatically downscales the image. Relative to designing native 16x16 icons, this downscaling makes lines really narrow.

Here is what happens with the buttons in Word 2016
Image of QAT in Word 2016

Compared to the downsized-Large icons on the left, the native small icons on the right are sharper and have clearer lines (particularly the citation icon when color-inverted). I tried to adjust line widths of the large citation icon, but couldn't find a width for the page symbol that both downsized nicely and looked good at Large size in the ribbon (which is obviously the priority). I understand that having two icons in the customize menu can be confusing. The somewhat nicer small icons might not be worth the hassle there. There are several development packages that extend the RibbonXML functionality to permit supplying two native icon sizes (e.g., Add-in Express), but they are quite expensive and not worth it unless their other features are also used (e.g., unified add-ins for 2003 and 2007+ versions, easier modification context menus and task panes). 

> This is addressing #16 , right? Most of these icons look good on the dark theme, except for the preferences ones. And Word seems to invert colours for the Unlink icon. Could we get the gear to invert too somehow?

Hmm, the color-inversion behavior is different on my installation of Word 2016 from yours. I am running Version 1611 (Build 7571.2109). In this build, third-party icons automatically invert when added to the QAT in Colorful, Dark Grey, and Black themes (as shown in the image above). What build are you running when the icons don't invert appropriately?

The difference in color-inversion behavior for Refresh/Unlink Citations buttons versus the others is that those two buttons use Microsoft-supplied default icons, rather than custom ones. The purpose of the custom icon for Document Preferences is to have a gear icon with Zotero branding (most preferences icons in Word have some sort of contextualization to distinguish them). If we don't need to have a Z on the icon, we can substitute in one of the default gears icons that will invert automatically on all Word versions like the Refresh/Unlink Citations icons.

**Comment by adomasven** [comment]
> Hmm, the color-inversion behavior is different on my installation of Word 2016 from yours. I am running Version 1611 (Build 7571.2109).

Yeah, I'm on an older version. Looks good once updated.

> Compared to the downsized-Large icons on the left, the native small icons on the right are sharper and have clearer lines (particularly the citation icon when color-inverted). 

My mistake. I confused the normal and downscaled icons. On the other hand, this is exactly my point about those being confusing.

> There are several development packages that extend the RibbonXML functionality to permit supplying two native icon sizes (e.g., Add-in Express), but they are quite expensive and not worth it unless their other features are also used (e.g., unified add-ins for 2003 and 2007+ versions, easier modification context menus and task panes).

I will look into coding this up myself. After looking at the MSDN docs it doesn't seem very difficult for something simple as supplying two different icons. I am not sure about Word 2007 compatibility though, so if it doesn't work I think it is better to avoid confusion in the customize menu, even if the icons downscale kinda bad.

**Comment by bwiernik** [comment]
>After looking at the MSDN docs it doesn't seem very difficult for something simple as supplying two different icons. 

From what I could find in the MSDN docs, it's possible to supply two icons for the general Windows Ribbon UI, but I don't think that functionality is available in the RibbonX that's implemented in Office. I might be wrong there though.

**Comment by adomasven** [comment]
> I will look into coding this up myself. After looking at the MSDN docs it doesn't seem very difficult for something simple as supplying two different icons. I am not sure about Word 2007 compatibility though, so if it doesn't work I think it is better to avoid confusion in the customize menu, even if the icons downscale kinda bad.

So this is actually kinda more involved than expected. Seems like you need to load the images by system path (can't load images bundled with Custom UI using VBA), so I'll comment out the small icons for now. The added confusion is not worth the improved looks (+ on HiDPI 125% or more the bigger icons in QAT look good).

CC @adam3smith @zuphilip @rmzelle :

Thinking about the combined bibliography button again - is there ever a reason where you would want to insert multiple bibliographies? Combining the bibliography button into Add/Edit would remove that possibility.

**Comment by adam3smith** [comment]
>Is there ever a reason where you would want to insert multiple bibliographies? 

Not given current Zotero capabilities, no. People ask about this, but it's in the context of having _separate_ bibliographies, e.g. per section, in the same document. 

And even _if_ you're going to add that functionality, there'd have to be a toggle for enabling "New Bibliography by section" or so somewhere, in which case the behavior of the button could be context depended. So yes to a merged button from my end.

Also agree Unlik Citations is much better than Remove Field Codes, although I'm still with @zuphilipp that moving that button somewhere a little less accessible might make sense UX-wise.

**Comment by bwiernik** [comment]
>Also agree Unlik Citations is much better than Remove Field Codes, although I'm still with @zuphilipp that moving that button somewhere a little less accessible might make sense UX-wise.

Perhaps a button in the Document Preferences pane instead? Labelled a longer explanation like "Unlink document from Zotero and stop updating"?

**Comment by adomasven** [comment]
>> Is there ever a reason where you would want to insert multiple bibliographies?

> Not given current Zotero capabilities, no.

Great, thanks.

> Also agree Unlik Citations is much better than Remove Field Codes, although I'm still with @zuphilipp that moving that button somewhere a little less accessible might make sense UX-wise.

Very good and I agree. This PR is mostly about changing the icons and merging the bibliography button. The discussion in #30 will be addressed separately, probably along with moving the Remove Field Codes button into preferences, but I will rename it now.

**Comment by rmzelle** [comment]
> Thinking about the combined bibliography button again - is there ever a reason where you would want to insert multiple bibliographies? Combining the bibliography button into Add/Edit would remove that possibility.

Well, the user could still copy and paste the bibliography field code to duplicate it, right? Maybe there are some rare cases where a user wishes to write an article with a bibliography, and supply the same bibliography in e.g. an appendix in the same document, but it's probably safe to ignore those. And the demand for something like that would be ever lower if Zotero supports document-based collections that include all items that have been cited in a document.

**Comment by rmzelle** [comment]
Also, and this is tangentially related to what the label of the "Refresh" button should be, does clicking "Refresh" also reload the citation style? If not, can it be changed to do that?

@adam3smith and others currently recommend users to switch to another style and back after updating a CSL style in Zotero, which isn't very obvious or quick (see e.g. https://forums.zotero.org/discussion/comment/212434/#Comment_212434). If the same could be achieved by clicking the "Refresh" button that seems much more straightforward.

**Comment by zuphilip** [comment]
👍 👍 👍  I agree on all points you said here today :)

**Comment by adomasven** [comment]
Closed with 9a3b764939

Thanks for the contribution @bwiernik and discussion everyone else.

**Comment by bwiernik** [comment]
Awesome! Thanks for finishing this up.

--
*Dr. Brenton Wiernik*
*Industrial-Organizational Psychologist*

Tel: +1 715-204-4252
Email: wiernik@workpsy.ch
URL: wiernik.workpsy.ch

**Pull request closed without merging**
