### PR TITLE
Add "Add or Edit Citation" macro

### PR DESCRIPTION
**Pull request by bwiernik**
Useful for programming a single Zotero keyboard shortcut. It's hidden
from the ribbon, but has an icon for use in user-specified Ribbon or QAT
customization. It uses the same choice logic as for displaying the ribbon icon.

### CODE REVIEW

**Comment by adam3smith** [comment]
FWIW, I've thought for a while that we should get rid of the edit citation button entirely and make it a context-dependent add/edit citation button.

**Comment by bwiernik** [comment]
The current plugin does that by changing the icon that is displayed in the ribbon. This allows the same functionality with a keyboard shortcut. We could, of course, make both buttons call the context-dependent macro so that we can eliminate the potentially confusing set of three macros from the list.

**Comment by bwiernik** [comment]
Per @adam3smith's recommendation, I switched the citation and bibliography macros to both be context-dependent. The ribbon macros now just switch the icons but both call the same macro (ZoteroCitation or ZoteroBibliography). This reduces the number of macros to 5. I made icons for the Add/Edit macros for use in user customization.

**Comment by adam3smith** [comment]
That was more an opinion than a recommendation -- we should make sure there's some agreement on this (and then also add it to the LO add-on).

**Comment by bwiernik** [comment]
(It is a pull request, so easy enough to reject if not desired. Mostly made it for my personal use and submitted if there was interest in implementing widely.)

**Comment by bwiernik** [comment]
@simonster

What are your thoughts on changing the macro to choose the appropriate add/edit functionality based on cursor position?

**Pull request closed without merging**
